# Generated by Django 6.0.4 on 2026-04-28 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('direccion', models.TextField(blank=True)),
                ('tipo_reserva', models.CharField(choices=[('alquiler', 'Alquiler'), ('servicio', 'Servicio'), ('evento', 'Evento Completo')], max_length=50)),
                ('fecha_evento', models.DateField()),
                ('descripcion', models.TextField(blank=True)),
                ('valor_total', models.IntegerField(default=0)),
                ('valor_anticipo', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('anticipo_pagado', 'Anticipo Pagado'), ('confirmada', 'Confirmada'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=50)),
                ('notas', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-creado'],
            },
        ),
    ]
