# Generated by Django 6.0.4 on 2026-04-28 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventoPortafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_evento', models.CharField(choices=[('boda', 'Boda'), ('quinceañera', 'Quinceañera'), ('fiesta', 'Fiesta'), ('corporativo', 'Corporativo'), ('otro', 'Otro')], max_length=50)),
                ('imagen', models.URLField()),
                ('fecha', models.DateField()),
                ('lugar', models.CharField(max_length=200)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evento del Portafolio',
                'verbose_name_plural': 'Eventos del Portafolio',
                'ordering': ['-fecha'],
            },
        ),
    ]
