# Generated by Django 6.0.4 on 2026-04-28 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoAlquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(choices=[('mobiliario', 'Mobiliario'), ('menaje', 'Menaje y Cristalería'), ('sonido', 'Sonido'), ('iluminacion', 'Iluminación'), ('decoracion', 'Decoración')], max_length=50)),
                ('precio', models.IntegerField()),
                ('unidad', models.CharField(default='por día', max_length=50)),
                ('imagen', models.URLField(blank=True)),
                ('disponible', models.BooleanField(default=True)),
                ('tipos_evento', models.JSONField(default=list)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Producto de Alquiler',
                'verbose_name_plural': 'Productos de Alquiler',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ServicioPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(choices=[('meseros', 'Meseros'), ('chef', 'Chef'), ('dj', 'DJ'), ('reposteria', 'Repostería'), ('fotografia', 'Fotografía'), ('floreria', 'Florería')], max_length=50)),
                ('precio', models.IntegerField()),
                ('unidad', models.CharField(default='por evento', max_length=50)),
                ('imagen', models.URLField(blank=True)),
                ('disponible', models.BooleanField(default=True)),
                ('tipos_evento', models.JSONField(default=list)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Servicio de Personal',
                'verbose_name_plural': 'Servicios de Personal',
                'ordering': ['categoria', 'nombre'],
            },
        ),
    ]
