# Generated by Django 6.0.4 on 2026-04-28 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo_evento', models.CharField(choices=[('boda', 'Boda'), ('quinceañera', 'Quinceañera'), ('fiesta', 'Fiesta'), ('corporativo', 'Corporativo'), ('otro', 'Otro')], max_length=50)),
                ('fecha_evento', models.DateField()),
                ('num_invitados', models.IntegerField()),
                ('municipio', models.CharField(max_length=100)),
                ('tiene_locacion', models.BooleanField(default=False)),
                ('servicios_interes', models.JSONField(default=list)),
                ('mensaje', models.TextField(blank=True)),
                ('atendido', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='MensajeContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('mensaje', models.TextField()),
                ('leido', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mensaje de Contacto',
                'verbose_name_plural': 'Mensajes de Contacto',
                'ordering': ['-creado'],
            },
        ),
    ]
